-- Opdracht 7: Maak een View voor deze informatiebehoefte (INDIVIDUEEL!)

DROP VIEW IF EXISTS dbo.Opdr7A_Omzet2015;
DROP VIEW IF EXISTS dbo.Opdr7B_MeestGehuurdeSpel;
DROP VIEW IF EXISTS dbo.Opdr7C_HuurovereenkomtHoogsteOmzet;
DROP VIEW IF EXISTS dbo.Opdr7D_TotaleSchade2016;
DROP VIEW IF EXISTS dbo.Opdr7E_ConsolesMetMeesteSchade;
GO

-- A. De omzet van de maand januari in het jaar 2015.
CREATE VIEW Opdr7A_Omzet2015 AS
  SELECT SUM(PRIJS) AS 'OMZET'
  FROM Omzet
  WHERE MONTH(DATUM) = 1 AND YEAR(DATUM) = 2015
GO

-- B. Het meest gehuurde Spel.
CREATE VIEW Opdr7B_MeestGehuurdeSpel AS
  SELECT TOP (1) WITH TIES
    TITEL,
    UITGEVER,
    JAAR_UITGAVE,
    COUNT(*) AS 'AANTAL_VERHUURD'
  FROM HistorieHuur
  WHERE TITEL IS NOT NULL
  GROUP BY TITEL, UITGEVER, JAAR_UITGAVE
  ORDER BY 'AANTAL_VERHUURD' DESC;
GO

-- C. De huurovereenkomst met de hoogste omzet.
CREATE VIEW Opdr7C_HuurovereenkomtHoogsteOmzet AS
  SELECT TOP (1) WITH TIES
    DATUM,
    EMAILADRES,
    SUM(PRIJS) AS 'TOTAAL'
  FROM HistorieHuur
  GROUP BY DATUM, EMAILADRES
  ORDER BY 'TOTAAL' DESC
GO

-- CREATE VIEW Opdr7C_HuurovereenkomtHoogsteOmzet AS
--   SELECT
--     HO.STARTDATUM,
--     HO.EMAILADRES,
--     SUM(DATEDIFF(D, HO.STARTDATUM, HO.EINDDATUM) * A.PRIJS_PER_D) AS 'totaal'
--   FROM ARTIKELENVERHUUR AS AV
--     INNER JOIN HUUROVEREENKOMST AS HO ON AV.EMAILADRES = HO.EMAILADRES AND AV.STARTDATUM = HO.STARTDATUM
--     INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
--   GROUP BY HO.EMAILADRES, HO.STARTDATUM
--   HAVING SUM(DATEDIFF(D, HO.STARTDATUM, HO.EINDDATUM) * A.PRIJS_PER_D) >= ALL (
--     SELECT SUM(DATEDIFF(D, HO.STARTDATUM, HO.EINDDATUM) * A.PRIJS_PER_D) AS 'totaal'
--     FROM ARTIKELENVERHUUR AS AV
--       INNER JOIN HUUROVEREENKOMST AS HO ON AV.EMAILADRES = HO.EMAILADRES AND AV.STARTDATUM = HO.STARTDATUM
--       INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
--     GROUP BY HO.EMAILADRES, HO.STARTDATUM
--   );
-- GO

-- D. De totale schade in het jaar 2016.
CREATE VIEW Opdr7D_TotaleSchade2016 AS
  SELECT SUM(R.KOSTEN) AS 'TOTALE_SCHADE'
  FROM REPARATIE AS R
  WHERE YEAR(R.STARTDATUM) = 2016;
GO

-- E. De consoles met de meeste schade.
CREATE VIEW Opdr7E_ConsolesMetMeesteSchade AS
  SELECT TOP (1) WITH TIES
    BARCODE,
    MERK,
    TYPE,
    SUM(PRIJS) AS 'KOSTEN'
  FROM HistorieReparatie
  GROUP BY BARCODE,
    MERK, TYPE
  ORDER BY KOSTEN DESC;
GO

-- CREATE VIEW Opdr7E_ConsolesMetMeesteSchade AS
--   SELECT
--     R.BARCODE,
--     A.MERK,
--     A.[TYPE],
--     SUM(R.KOSTEN) AS 'KOSTEN'
--   FROM REPARATIE AS R
--     INNER JOIN ARTIKEL AS A ON R.BARCODE = A.BARCODE
--   GROUP BY R.BARCODE, A.MERK, A.[TYPE]
--   HAVING SUM(R.KOSTEN) >= ALL (
--     SELECT SUM(R.KOSTEN) AS 'kosten'
--     FROM REPARATIE AS R
--       INNER JOIN ARTIKEL AS A ON R.BARCODE = A.BARCODE
--     WHERE A.SPEL_OF_CONSOLE = 'CONSOLE'
--     GROUP BY R.BARCODE
--   );
-- GO