-- Opdracht 8: Implementeer een ontworpen scherm in Access met een Master-Detail-oplossing (INDIVIDUEEL!)

USE gameparadisespring

DROP VIEW IF EXISTS dbo.Opdr8_HuurHistorie;
DROP VIEW IF EXISTS dbo.Opdr8_OmzetKlantPerJaar;
DROP VIEW IF EXISTS dbo.Opdr8_Klantstatus;
GO

-- Master view:
-- Klanten overzicht
--
-- Detail view:
-- huurhistorie
-- omzet v/d klant /jaar
-- klantstatus
--
-- Op basis daarvan krijgt een klant een status van Gold, Silver of Bronze. Het totaal bestede bedrag over de afgelopen 12 maanden is hiervoor bepalend: Gold klanten hebben 150 euro besteed, Silver 100 en Bronze 50.

-- Huurhistory
CREATE VIEW Opdr8_HuurHistorie AS
  SELECT
    A.BARCODE,
    A.MERK,
    A.[TYPE],
    A.TITEL,
    A.UITGEVER,
    A.JAAR_UITGAVE,
    HO.STARTDATUM,
    HO.EINDDATUM,
    DATEDIFF(D, HO.STARTDATUM, HO.EINDDATUM) * A.PRIJS_PER_D AS 'KOSTEN',
    HO.EMAILADRES
  FROM HUUROVEREENKOMST AS HO
    LEFT JOIN ARTIKELENVERHUUR AS AVR ON HO.EMAILADRES = AVR.EMAILADRES AND HO.STARTDATUM = AVR.STARTDATUM
    LEFT JOIN ARTIKEL A ON AVR.BARCODE = A.BARCODE;
GO

-- omzet v/d klant /jaar
CREATE VIEW Opdr8_OmzetKlantPerJaar AS
  -- Omzet per klant per jaar verhuur
  SELECT
    EMAILADRES,
    JAAR,
    SUM(OMZET) AS 'OMZET'
  FROM
    (SELECT
       HO.EMAILADRES,
       YEAR(HO.STARTDATUM) AS 'JAAR',
       (SELECT SUM(DATEDIFF(D, HO1.STARTDATUM, HO1.EINDDATUM) * A.PRIJS_PER_D)
        FROM HUUROVEREENKOMST AS HO1
          LEFT JOIN ARTIKELENVERHUUR AS AVR ON HO1.EMAILADRES = AVR.EMAILADRES AND HO1.STARTDATUM = AVR.STARTDATUM
          LEFT JOIN ARTIKEL A ON AVR.BARCODE = A.BARCODE
        WHERE HO1.EMAILADRES = HO.EMAILADRES
              AND YEAR(HO1.STARTDATUM) = YEAR(HO.STARTDATUM)
       )                   AS 'OMZET'
     FROM HUUROVEREENKOMST AS HO
       LEFT JOIN ARTIKELENVERHUUR AS AVR ON HO.EMAILADRES = AVR.EMAILADRES AND HO.STARTDATUM = AVR.STARTDATUM
       LEFT JOIN ARTIKEL A ON AVR.BARCODE = A.BARCODE
     GROUP BY HO.EMAILADRES, YEAR(HO.STARTDATUM)
     UNION ALL
     -- Omzet per klant per jaar verhuur
     SELECT
       VO.EMAILADRES,
       YEAR(VO.DATUM) AS 'JAAR',
       (SELECT SUM(A.PRIJS)
        FROM VERKOOPOVEREENKOMST AS VO1
          LEFT JOIN ARTIKELENVERKOOP AS AV ON VO1.EMAILADRES = AV.EMAILADRES AND VO1.DATUM = AV.DATUM
          LEFT JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
        WHERE VO.EMAILADRES = VO1.EMAILADRES
              AND YEAR(VO.DATUM) = YEAR(VO1.DATUM)
       )              AS 'OMZET'
     FROM VERKOOPOVEREENKOMST AS VO
       LEFT JOIN ARTIKELENVERKOOP AS AV ON VO.EMAILADRES = AV.EMAILADRES AND VO.DATUM = AV.DATUM
       LEFT JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
     GROUP BY VO.EMAILADRES, YEAR(VO.DATUM)
     UNION ALL
     -- Omzet per klant per jaar reparatie
     SELECT
       AV.EMAILADRES,
       YEAR(R.STARTDATUM) AS 'JAAR',
       (SELECT SUM(R.KOSTEN)
        FROM REPARATIE AS R1
          INNER JOIN ARTIKELENVERHUUR AS AV1 ON R1.BARCODE = AV1.BARCODE AND R1.STARTDATUM = AV1.STARTDATUM
        WHERE AV.EMAILADRES = AV1.EMAILADRES
              AND YEAR(R.STARTDATUM) = YEAR(R1.STARTDATUM)
       )                  AS 'OMZET'
     FROM REPARATIE AS R
       INNER JOIN ARTIKELENVERHUUR AS AV ON R.BARCODE = AV.BARCODE AND R.STARTDATUM = AV.STARTDATUM
     GROUP BY AV.EMAILADRES, YEAR(R.STARTDATUM)
    ) AS OMZET
  GROUP BY EMAILADRES, JAAR;
GO

CREATE VIEW Opdr8_Klantstatus AS
  -- Omzet per klant per jaar verhuur
  SELECT
    EMAILADRES,
    SUM(OMZET)       AS 'OMZET',
    CASE
    WHEN SUM(OMZET) >= 150
      THEN 'Gold'
    WHEN SUM(OMZET) >= 100
      THEN 'Silver'
    ELSE 'Brons' END AS 'STATUS'
  FROM (
         SELECT
           HO.EMAILADRES,
           (SELECT SUM(DATEDIFF(D, HO1.STARTDATUM, HO1.EINDDATUM) * A.PRIJS_PER_D)
            FROM HUUROVEREENKOMST AS HO1
              LEFT JOIN ARTIKELENVERHUUR AS AVR ON HO1.EMAILADRES = AVR.EMAILADRES AND HO1.STARTDATUM = AVR.STARTDATUM
              LEFT JOIN ARTIKEL A ON AVR.BARCODE = A.BARCODE
            WHERE HO1.EMAILADRES = HO.EMAILADRES
                  AND HO1.STARTDATUM > DATEADD(YEAR, -1, GETDATE())
           ) AS 'OMZET'
         FROM HUUROVEREENKOMST AS HO
           LEFT JOIN ARTIKELENVERHUUR AS AVR ON HO.EMAILADRES = AVR.EMAILADRES AND HO.STARTDATUM = AVR.STARTDATUM
           LEFT JOIN ARTIKEL A ON AVR.BARCODE = A.BARCODE
         WHERE HO.STARTDATUM > DATEADD(YEAR, -1, GETDATE())
         GROUP BY HO.EMAILADRES
         UNION ALL
         -- Omzet per klant per jaar verhuur
         SELECT
           VO.EMAILADRES,
           (SELECT SUM(A.PRIJS)
            FROM VERKOOPOVEREENKOMST AS VO1
              LEFT JOIN ARTIKELENVERKOOP AS AV ON VO1.EMAILADRES = AV.EMAILADRES AND VO1.DATUM = AV.DATUM
              LEFT JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
            WHERE VO.EMAILADRES = VO1.EMAILADRES
                  AND VO1.DATUM > DATEADD(YEAR, -1, GETDATE())
           ) AS 'OMZET'
         FROM VERKOOPOVEREENKOMST AS VO
           LEFT JOIN ARTIKELENVERKOOP AS AV ON VO.EMAILADRES = AV.EMAILADRES AND VO.DATUM = AV.DATUM
           LEFT JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
         WHERE VO.DATUM > DATEADD(YEAR, -1, GETDATE())
         GROUP BY VO.EMAILADRES
         UNION ALL
         -- Omzet per klant per jaar reparatie
         SELECT
           AV.EMAILADRES,
           (SELECT SUM(R.KOSTEN)
            FROM REPARATIE AS R1
              INNER JOIN ARTIKELENVERHUUR AS AV1 ON R1.BARCODE = AV1.BARCODE AND R1.STARTDATUM = AV1.STARTDATUM
            WHERE AV.EMAILADRES = AV1.EMAILADRES
                  AND R1.STARTDATUM > DATEADD(YEAR, -1, GETDATE())
           ) AS 'OMZET'
         FROM REPARATIE AS R
           INNER JOIN ARTIKELENVERHUUR AS AV ON R.BARCODE = AV.BARCODE AND R.STARTDATUM = AV.STARTDATUM
         WHERE R.STARTDATUM > DATEADD(YEAR, -1, GETDATE())
         GROUP BY AV.EMAILADRES, YEAR(R.STARTDATUM)
       ) AS OMZET
  GROUP BY EMAILADRES;
GO


