-- CREATE VIEW Henk AS
-- SELECT K.EMAILADRES, ACHTERNAAM, T.TELNUMMER FROM KLANT AS K
-- INNER JOIN KLANTTELEFOONNR K2 ON K.EMAILADRES = K2.EMAILADRES
-- INNER JOIN TELEFOONNUMMER T ON K2.TELNUMMER = T.TELNUMMER
--
-- CREATE VIEW Piet AS
-- SELECT * FROM ARTIKEL AS A

CREATE DATABASE GAMEPARADISE