/*================================================================*/
/* Database name:  GameParadise			                          */
/* DBMS name:      Microsoft SQL Server 2017                      */
/* Created on:     20/12/2017							          */
/* Made by:        Martijn de Geus, Nick Hartjes en Joey Stoffels */
/*================================================================*/

USE GAMEPARADISE
GO

-- Opdracht 6: Maak queries voor het genereren van overzichten (GROEP)
-- A. Alle artikelen in voorraad gesorteerd naar soort, merk en type. Dus die artikelen die op het moment niet verkocht of verhuurd zijn.
SELECT A.BARCODE
    , A.MERK
    , A.TYPE
    , A.TITEL
    , A.PRIJS
    , A.PRIJS_PER_D
    , A.SPEL_OF_CONSOLE
    , A.JAAR_UITGAVE
    , A.UITGEVER
FROM ARTIKEL AS A
WHERE BARCODE NOT IN (
    SELECT BARCODE FROM ARTIKELENVERHUUR AS AV
    INNER JOIN HUUROVEREENKOMST AS HO ON (AV.EMAILADRES = HO.EMAILADRES AND AV.STARTDATUM = HO.STARTDATUM)
    WHERE HO.HUURSTATUS = 'VERHUURD' AND HO.STARTDATUM <= GETDATE() AND HO.EINDDATUM >= GETDATE()
) AND BARCODE NOT IN (
    SELECT BARCODE FROM ARTIKELENVERKOOP AS AV
    INNER JOIN VERKOOPOVEREENKOMST AS VO ON (AV.EMAILADRES = VO.EMAILADRES AND AV.DATUM = VO.DATUM)
)
ORDER BY SPEL_OF_CONSOLE ASC, MERK ASC, TYPE ASC;

-- Check:
SELECT COUNT(*) FROM ARTIKEL;

SELECT COUNT(BARCODE) FROM ARTIKELENVERHUUR AS AV
INNER JOIN HUUROVEREENKOMST AS HO ON (AV.EMAILADRES = HO.EMAILADRES AND AV.STARTDATUM = HO.STARTDATUM)
WHERE HO.HUURSTATUS = 'VERHUURD' AND HO.STARTDATUM <= GETDATE() AND HO.EINDDATUM >= GETDATE()

SELECT COUNT(BARCODE) FROM ARTIKELENVERKOOP AS AV
INNER JOIN VERKOOPOVEREENKOMST AS VO ON (AV.EMAILADRES = VO.EMAILADRES AND AV.DATUM = VO.DATUM)


-- B. Alle Consoles die in 2016 schade hebben gehad.
SELECT A.BARCODE
    , A.MERK
    , A.TYPE
    , A.TITEL
    , A.PRIJS
    , A.PRIJS_PER_D
    , A.SPEL_OF_CONSOLE
    , A.JAAR_UITGAVE
    , A.UITGEVER
FROM REPARATIE AS R
INNER JOIN ARTIKEL AS A ON R.BARCODE = A.BARCODE 
WHERE A.SPEL_OF_CONSOLE = 'CONSOLE' AND (YEAR(R.STARTDATUM) = 2016 OR YEAR(R.DATUM_GEREED) = 2016);


-- C. Alle klanten die momenteel een Console hebben gehuurd. Welke klant heeft welke console gehuurd.
SELECT K.EMAILADRES
    , K.VOORNAMEN
    , K.ACHTERNAAM 
    , A.MERK
    , A.[TYPE]
FROM HUUROVEREENKOMST AS HO
INNER JOIN ARTIKELENVERHUUR AS AV ON (HO.STARTDATUM = AV.STARTDATUM AND HO.EMAILADRES = AV.EMAILADRES)
INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
INNER JOIN KLANT AS K ON HO.EMAILADRES = K.EMAILADRES
WHERE A.SPEL_OF_CONSOLE = 'CONSOLE' AND HO.STARTDATUM <= GETDATE() AND HO.EINDDATUM >= GETDATE() AND HO.HUURSTATUS = 'VERHUURD';

-- D. De artikelen die verhuurd zijn in mei 2015.
SELECT A.BARCODE
    , A.MERK
    , A.TYPE
    , A.TITEL
    , A.PRIJS
    , A.PRIJS_PER_D
    , A.SPEL_OF_CONSOLE
    , A.JAAR_UITGAVE
    , A.UITGEVER
FROM HUUROVEREENKOMST AS HO 
INNER JOIN ARTIKELENVERHUUR AS AV ON (HO.STARTDATUM = AV.STARTDATUM AND HO.EMAILADRES = AV.EMAILADRES)
INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
WHERE (MONTH(HO.STARTDATUM) = 5 AND YEAR(HO.STARTDATUM) = 2015) OR (MONTH(HO.EINDDATUM) = 5 AND YEAR(HO.EINDDATUM) = 2015);

-- E. De huurovereenkomsten waarin een Playstation is gehuurd.
SELECT HO.STARTDATUM
    , HO.EMAILADRES
    , HO.EINDDATUM
    , HO.HUURSTATUS
    , HO.SCHADE
    , HO.REPARABEL
	, A.[TYPE]
	, A.MERK
FROM HUUROVEREENKOMST AS HO 
INNER JOIN ARTIKELENVERHUUR AS AV ON (HO.STARTDATUM = AV.STARTDATUM AND HO.EMAILADRES = AV.EMAILADRES)
INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
WHERE A.[TYPE] LIKE 'PS%';

-- F. Alle klanten die in 2017 iets gekocht of gehuurd hebben. Deze willen we namelijk een kerstkaart sturen.
SELECT K.EMAILADRES
      , K.MERK_EIGEN_CONSOLE
      , K.TYPE_EIGEN_CONSOLE
      , K.VOORNAMEN
      , K.ACHTERNAAM
      , K.STRAATNAAM
      , K.HUISNUMMER
      , K.POSTCODE
      , K.WOONPLAATS
      , K.GEBOORTEDATUM
      , K.GESLACHT
      , K.WACHTWOORD
FROM KLANT AS K
WHERE K.EMAILADRES IN (
    SELECT HO.EMAILADRES
    FROM HUUROVEREENKOMST AS HO
    INNER JOIN ARTIKELENVERHUUR AS AV ON (HO.STARTDATUM = AV.STARTDATUM AND HO.EMAILADRES = K.EMAILADRES)
    WHERE YEAR(HO.STARTDATUM) = 2017 OR YEAR(HO.EINDDATUM) = 2017
) OR  K.EMAILADRES IN (
    SELECT VO.EMAILADRES
    FROM VERKOOPOVEREENKOMST AS VO
    WHERE YEAR(VO.DATUM) = 2017
);