USE GAMEPARADISE

-- Master view:
-- 8A: Klanten overzicht.
CREATE VIEW OPDRACHT_8A AS
SELECT * FROM KLANT;

-- Detail view:
-- 8B: Huurhistorie van de klant.
CREATE VIEW OPDRACHT_8B AS
SELECT
      K.[EMAILADRES],
      HO.[STARTDATUM],
      A.[BARCODE],
      (CONVERT(INT, HO.[EINDDATUM] - HO.[STARTDATUM]) * A.[PRIJS_PER_D]) AS 'BEDRAG'
FROM
      ARTIKELENVERHUUR AV
      INNER JOIN ARTIKEL A ON A.[BARCODE] = AV.[BARCODE]
      INNER JOIN KLANT K ON K.[EMAILADRES] = AV.[EMAILADRES] AND K.[EMAILADRES] = AV.[EMAILADRES]
      INNER JOIN HUUROVEREENKOMST HO ON HO.[EMAILADRES] = AV.[EMAILADRES] AND HO.[STARTDATUM] = AV.[STARTDATUM]
      ORDER BY K.EMAILADRES ASC, HO.[STARTDATUM] DESC, A.[BARCODE] ASC;


-- 8C: Omzet van de klant per jaar.
CREATE VIEW OPDRACHT_8C AS
SELECT
      K.[EMAILADRES],
      A.[BARCODE],
      AV.STARTDATUM,
      AK.DATUM

FROM
      ARTIKEL A
      INNER JOIN ARTIKELENVERHUUR AV ON A.BARCODE = AV.BARCODE
      INNER JOIN HUUROVEREENKOMST HO ON HO.[EMAILADRES] = AV.[EMAILADRES] AND HO.[STARTDATUM] = AV.[STARTDATUM]
      INNER JOIN ARTIKELENVERKOOP AK ON A.[BARCODE] = AK.[BARCODE]
      INNER JOIN VERKOOPOVEREENKOMST VO ON AK.[EMAILADRES] = VO.[EMAILADRES] AND AK.[DATUM] = VO.[DATUM]
      INNER JOIN KLANT K ON HO.[EMAILADRES] = K.[EMAILADRES]
      ORDER BY K.EMAILADRES;

  (SELECT COALESCE((SELECT SUM(CONVERT(INT, HO.[EINDDATUM] - HO.[STARTDATUM]) * A.[PRIJS_PER_D])
                    FROM ARTIKEL A
                      INNER JOIN ARTIKELENVERHUUR AV ON A.[BARCODE] = AV.[BARCODE]
                      INNER JOIN HUUROVEREENKOMST HO ON AV.[EMAILADRES] = HO.EMAILADRES AND AV.[STARTDATUM] = HO.[STARTDATUM]
                    WHERE MONTH(AV.[STARTDATUM]) = 1 AND YEAR(AV.[STARTDATUM]) = 2015),	0) AS 'VERHUUR') AS A1,

  (SELECT COALESCE((SELECT SUM(A.[PRIJS])
                    FROM ARTIKEL A
                      INNER JOIN ARTIKELENVERKOOP AK ON A.[BARCODE] = AK.[BARCODE]
                      INNER JOIN VERKOOPOVEREENKOMST VO ON AK.[EMAILADRES] = VO.[EMAILADRES] AND AK.[DATUM] = VO.[DATUM]
                    WHERE MONTH(AK.[DATUM]) = 1 AND YEAR(AK.[DATUM]) = 2015), 0) AS 'VERKOOP') AS B2,

  (SELECT COALESCE((SELECT SUM(R.[KOSTEN])
                    FROM REPARATIE R
                    WHERE MONTH(R.[STARTDATUM]) = 1 AND YEAR(R.[STARTDATUM]) = 2015), 0) AS 'REPARATIE') AS C3;

-- 8D: Klantstatus van de klant.
CREATE VIEW OPDRACHT_8D AS
