-- Opdracht 7: Maak een View voor deze informatiebehoefte (INDIVIDUEEL!)

USE GAMEPARADISE

-- A. De omzet van de maand januari in het de jaar 2015.

-- Hierbij is de aanname gedaan dat er op de startdatum van huurovereenkomst betaald word.
SELECT TOP(1)
(SELECT SUM(DATEDIFF(d, HO.STARTDATUM, HO.EINDDATUM) * A.PRIJS_PER_D)
FROM ARTIKELENVERHUUR AS AV
INNER JOIN HUUROVEREENKOMST AS HO ON (AV.EMAILADRES = HO.EMAILADRES AND AV.STARTDATUM = HO.STARTDATUM)
INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
WHERE HO.HUURSTATUS = 'VERHUURD' AND YEAR(HO.STARTDATUM) = '2015' AND MONTH(HO.STARTDATUM) = '1') AS 'verhuur'
,
(SELECT SUM(A.PRIJS) FROM ARTIKELENVERKOOP AS AV
INNER JOIN VERKOOPOVEREENKOMST AS VO ON (AV.EMAILADRES = VO.EMAILADRES AND AV.DATUM = VO.DATUM)
INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
WHERE YEAR(VO.DATUM) = '2015' AND MONTH(VO.DATUM) = '1') AS 'verkoop'
FROM ARTIKEL


SELECT *
FROM ARTIKEL AS A
LEFT JOIN REPARATIE AS R ON A.BARCODE = R.BARCODE
LEFT JOIN ARTIKELENVERKOOP AS AV ON A.BARCODE = AV.BARCODE
LEFT JOIN ARTIKELENVERHUUR AS AVR ON A.BARCODE = AVR.BARCODE
LEFT JOIN HUUROVEREENKOMST AS HO ON AVR.BARCODE = HO.EMAILADRES



-- B. Het meest gehuurde Spel.
SELECT AV.BARCODE, COUNT(AV.BARCODE) AS 'keren verhuurd'
FROM ARTIKELENVERHUUR AS AV
INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
WHERE A.SPEL_OF_CONSOLE = 'SPEL'
GROUP BY AV.BARCODE
HAVING COUNT(AV.BARCODE) >= All (
    SELECT COUNT(AV.BARCODE)
    FROM ARTIKELENVERHUUR AS AV
    INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
    WHERE A.SPEL_OF_CONSOLE = 'SPEL'
    GROUP BY AV.BARCODE)


-- C. De huurovereenkomst met de hoogste omzet.
SELECT HO.EMAILADRES 
    , HO.STARTDATUM
    , SUM(DATEDIFF(d, HO.STARTDATUM, HO.EINDDATUM) * A.PRIJS_PER_D) AS 'totaal'
FROM ARTIKELENVERHUUR AS AV
INNER JOIN HUUROVEREENKOMST AS HO ON AV.EMAILADRES = HO.EMAILADRES AND AV.STARTDATUM = HO.STARTDATUM
INNER JOIN ARTIKEL AS A ON AV.BARCODE = A.BARCODE
GROUP BY HO.EMAILADRES, HO.STARTDATUM
ORDER BY 'totaal' DESC



-- D. De totale schade in het jaar 2016.

-- E. De consoles met de meeste schade.